### ISSUE TITLE
Question regarding select

### ISSUE THREAD

**Issue by softgripper** [dmaevsky/tinyx#7]
Firstly, great library.  Really interesting :)

I'm writing an idle/clicker game in svelte.  My data structure is as follows

```javascript
import {tx, select} from 'tinyx'

const initialState = {
  primaryCurrency: 0,
  generators: [
    {
      name: '🐖 Pig',
      count: 0,
      cost: 4,
    },
    {
      name: '🍞 Bread',
      count: 0,
      cost: 5,
    },
  ],
};

const state = tx(initialState);

const ADD_PRIMARY_CURRENCY = (amount) => {
  return ({ update }) =>
    update(
      'primaryCurrency',
      (primaryCurrency) => primaryCurrency + amount
    );
};

const BUY_GENERATOR = (amount) => {
  return ({ update }) => update('count', (count) => count + amount);
};


// this is inside a generator component that takes an index of the generators location in the state
const generator = select(state, () => ['generators', index])
```

My question is, how do I apply an update to primaryCurrency when I modify the generator.

At the moment I can do
```javascript
state.commit(ADD_PRIMARY_CURRENCY, -generator.cost) // this works
generator.commit(BUY_GENERATOR, 1) // this works
```

But I'd like to put the update to ADD_PRIMARY_CURRENCY inside BUY_GENERATOR somehow - or group them so there is a single commit to the state (preferably only calling a commit on the result of the generator select.

**Comment by dmaevsky** [comment]
Looks like your generator component needs access to the root store anyway in order to be able to update `primaryCurrency`, so in this case it does not make much sense to use `select` at all. I would do:
```js
function BUY_GENERATOR({ index, amount }) {
  return ({ get, update, apply }) => {
    update('generators', index, 'count', (count) => count + amount);
    apply(ADD_PRIMARY_CURRENCY( -amount * get('generators', index, 'cost') );
};
```
and commit it to the root store directly:
```js
store.commit(BUY_GENERATOR, { index, amount });
``` 

`select` only helps when you have a semantically isolated state sub-tree.

On a side note: using `function` keyword for your mutations is a good practice, since it gives them a `name` that `tinyx/middleware/logger` would be able to log to your console: helps tremendously in debugging.

**Comment by softgripper** [comment]
Thanks, that makes sense

> On a side note: using `function` keyword for your mutations is a good practice, since it gives them a `name` that `tinyx/middleware/logger` would be able to log to your console: helps tremendously in debugging.

I did read that in the README.  Currently I'm using the logger, and the output is this (with my consts) so I didn't bother changing them. :)

![logger](https://user-images.githubusercontent.com/26377893/111892854-1427bf80-8a53-11eb-9f89-6017dc446ef7.png)

**Comment by dmaevsky** [comment]
Ah right, with the `const name = func` syntax the runtime attaches `name` to `func` as well. Even better :)
Closing this for now, if you don't mind...
